version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      #- $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - sam build --no-cached
      - sam deploy --no-confirm-changeset
